version: '3'
services:
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - "db"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: go_database
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    # command: --default-authentication-plugin=mysql_native_password
    # ↑のコマンド実行しても変わらんから、mysql入って手動で変えろ！
    # mysql -uroot -proot -h 127.0.0.1 --port 3308
    # command: ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  db-data: